### ISSUE TITLE
Crash on Volumio Buster with Radio Paradise plugin

### ISSUE THREAD

**Issue by avjui** [Maschine2501/NR1-UI#8]
With the Radio Paradise plugin I got a crash
```Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "nr1ui.py", line 569, in display_update_service
    oled.modal.DrawOn(image)
  File "nr1ui.py", line 3130, in DrawOn
    if ScrollSpecsFirstRound == True:
UnboundLocalError: local variable 'ScrollSpecsFirstRound' referenced before assignment
```
After Insert following lines after line 972 in nr1ui.py the crash is gone for me
```
        global ScrollSpecsFirstRound
        global ScrollSpecsNextRound
        global ScrollSpecsTag
        global ScrollSpecsNext
```

**Comment by Maschine2501** [comment]
@avjui Hi!
Sorry for the late answer.
Ist the Issue still persistent on newest Volumio/newest NR1-UI?
Cheers
